apiVersion: launchpad.mirantis.com/mke/v1.4
kind: mke
metadata:
  name: my-mke-cluster
spec:
  hosts:
  - ssh:
      address: ec2-51-112-18-14.me-central-1.compute.amazonaws.com
      user: ubuntu
      #port: 22
      keyPath: /home/ubuntu/.ssh/id_rsa
    role: manager
  - ssh:
      address: ec2-3-29-70-34.me-central-1.compute.amazonaws.com
      user: ubuntu
      port: 22
      keyPath: /home/ubuntu/.ssh/id_rsa
    role: worker
  - ssh:
      address: ec2-3-28-93-144.me-central-1.compute.amazonaws.com
      user: ubuntu
      port: 22
      keyPath: /home/ubuntu/.ssh/id_rsa
    role: worker
  mke:
    version: 3.7.2
    installFlags:
    - --default-node-orchestrator=kubernetes
    - --pod-cidr 10.0.0.0/16
    - --admin-username admin
    - --admin-password Timeline
  mcr:
    version: 23.0.8
  cluster:
    prune: false