apiVersion: launchpad.mirantis.com/mke/v1.4
kind: mke
metadata:
  name: my-mke-cluster
spec:
  hosts:
  - ssh:
      address: 172.31.7.138
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: manager
  - ssh:
      address: 172.31.9.50
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
  - ssh:
      address: 172.31.12.84
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
  mke:
    version: 3.7.2
    installFlags:
    - --pod-cidr="10.0.0.0/16"
    - --admin-username=admin
    - --admin-password=Timeline
  mcr:
    version: 20.10.13
  cluster:
    prune: false